### ISSUE TITLE
add flow for lower feather site to standard flow

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#118]

**Comment by alvizek** [comment]
Find a flow gage (USGS or CDEC) that represents the Lower Feather RST site (not on monitoring map!) - below the confluence of the Yuba River and Feather River but not on the Sacramento River. If there is not a gage we can add up the Yuba and the High Flow Feather (e.g. Gridley gage). Add code to this file: https://github.com/SRJPE/JPE-datasets/blob/main/data-raw/standard-format-data-prep/flow_standard_format.Rmd

**Comment by B-yunes** [comment]
There was already a gage from CDEC (FSB). I checked other gage from CDEC and two from USGS to verify that CDEC gage being used was the best (FSB). Cleaned flow data prep and standard flow to clearly show data source selected. Update on changes pushed to covariate-processing branch.

**Comment by alvizek** [comment]
I reviewed the pull request that included this change and this can now be closed.
