### ISSUE TITLE
credible intervals for passage estimates

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#151]
If possible try to get credible intervals for passage estimates:
- battle
- butte
- clear
- deer
- mill
- yuba

**Comment by liz-fw** [comment]
e-mailed Grant for Butte estimates 11-28-2023

**Comment by alvizek** [comment]
Ashley and Liz discussed and we will ask about CIs during Adult Next Steps meetings

**Comment by liz-fw** [comment]
Update: `Battle Creek` does not have credible intervals
Update: `Yuba` does not have credible intervals - analysis is combination of two non-parametric analyses, so can't combine statistical error without a bigger analysis that they haven't done.
Update: Doug Killam has files with `Deer Creek` and `Mill Creek` 90% Confidence Intervals
