### ISSUE TITLE
year selection analysis for adult data

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#158]
Conduct analysis similar to what we did for RST to remove years that are not representative. Also exclude data types that are not representative.

**Comment by ErinCain** [comment]
Dropping some ideas for exclusion criteria here

Survey data 
- Exclude year if survey does not cover all reaches in a year 

Video data
- Exclude year if video out for more than 2 weeks in the sampling season 
- Exclude year if flows exceed X value on each trip (overpass weir etc..)

**Comment by alvizek** [comment]
Conclusions from this analysis
- how many years would we have to exclude and in what tribs

This will help us identify where we need to come up with interpolation and we discuss how many resources to do this

**Comment by ErinCain** [comment]
The first iteration is complete, I created a years-to-exclude spreadsheet and cleaned up the vignette. After each analysis is included in standard data I will go through one more time and finalize the vignette https://docs.google.com/spreadsheets/d/1AlkszjqLdCLwh--DtP2cVnOO0CjpVBr-TRd9tqg0LnA/edit
