### ISSUE TITLE
cross check the battle and clear RST with EDI to confirm all runs

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#159]
one final check to make sure we have all the runs for battle and clear

**Comment by ErinCain** [comment]
Looks like for the same date ranges Battle EDI version has: 
fall       late-fall    spring    winter 
1717       633       28546       363 

And our data has: 
fall       late fall    spring    winter 
1443       635     29396       361

So they do not align all the way and in total there is about a 575 fish difference (total of 31,259 vs 31,835). The ratios change a little bit when using the whole database that spans back longer and extends to include the 2022 monitoring season so it is likely a good idea to update to the tables on EDI anyways.

**Comment by ErinCain** [comment]
And on Clear we see an even bigger difference
edi data: 
fall          late-fall    spring    winter 
110795      6911     32482        90

our data: 
fall              late fall    spring    winter 
223307     13808     65368       186 

Looks like we just have almost double everything in our version...I will dig into what could be causing this.

**Comment by alvizek** [comment]
Next steps
- check if the standard format is using the wrong run or why it is so different that raw. there could also be a messy join happening when adding catch = 0

**Comment by ErinCain** [comment]
I think what is happening is that the high values showing up on EDI and in qc markdown include catch = 0 rows. In standard catch we do not include those rows
