### ISSUE TITLE
yuba river passage - entries where hours 0 and count = 1

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#169]
There are 249 entries for Yuba River where hours is 0 but count is greater than 0 which doesn't make sense. Confirm that these counts are real.

**Comment by alvizek** [comment]
This is likely interpolated data from passage estimates.

TODO - double check that this is not in the raw data. If not, then close.

**Comment by ErinCain** [comment]
Looks like there are quite a few passage records where hours are 0 and count is 1 (814) - this occurs in the raw passage data.

**Comment by ErinCain** [comment]
These exist in the original dataset. Looks like a couple of things could be going on:
1) there is an error in the operations data (date, hours fished, ladder) that we join to the passage data. Hours fished are off with the operations data. 
2) There could be an error with the passage data...assigned to wrong date or wrong ladder. 

I will add this to the email to Brian.
