### ISSUE TITLE
add confidence intervals for CJS estimates

### ISSUE THREAD

**Issue by liz-fw** [SRJPE/JPE-datasets#173]
reach out to streams to get their CJS estimate confidence intervals

**Comment by alvizek** [comment]
- We are just waiting to hear from Grant about this

**Comment by alvizek** [comment]
Ask Grant about this again during the EDI package review meeting

**Comment by liz-fw** [comment]
done in `jpe-butte-adult-edi` and needs to be incorporated in `standard-format`. stored in google bucket for now
