### ISSUE TITLE
dig into yuba river upstream passage data to understand data gaps

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#183]
Erin and I noticed big data gaps between the assumed Mar-May migration period and consistent sampling outside of this period. What is going on? 
- Look at the raw data
- Read the report on their interpolation method

**Comment by ErinCain** [comment]
Plot shows that their early window is may/june - mid July. Is this when the spring run are moving? 

![Image](https://github.com/SRJPE/JPE-datasets/assets/51136638/14776d3e-cbec-455f-a09d-9ded5f8d5ce3)

**Comment by ErinCain** [comment]
Erin to follow up with an email to Brian.

**Comment by ErinCain** [comment]
Yuba considers upstream passage to be a census for spring run in all years except:
- north ladder closure Feb-Sept during 2019; 
- 3 years where there is no run differentiation (which are these?) 
- 2016-2017 the GAM could not be applied

**Comment by alvizek** [comment]
- Note that we want to check these issues with the data used for the EDI package (wait to confirm with Yuba that using correct data)
